### ISSUE TITLE
BUG: Users Unable to Deposit `jEUR/PAR` and `jEUR-EURT`

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1006]
https://app.beefy.finance/vault/jarvis-2eurp

https://app.beefy.finance/vault/jarvis-2eurt

<img width="1322" alt="Screenshot 2022-11-15 at 09 25 16" src="https://user-images.githubusercontent.com/839848/201867948-a1a8049c-5f33-40a8-ac34-35afd6e9ed5d.png">

**Comment by peetzweg** [comment]
This is the error user get

```
{"reason":"execution reverted: DMMLibrary: INSUFFICIENT_LIQUIDITY","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x2924973E3366690eA7aE3FCdcb2b4e136Cf7f8Cc","to":"0x30b32BbfcA3A81922F88809F53E625b5EE5286f6","data":"0xa0712d68000000000000000000000000000000000000000000000000004701979117baf9","accessList":null},"error":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: DMMLibrary: INSUFFICIENT_LIQUIDITY","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022444d4d4c6962726172793a20494e53554646494349454e545f4c49515549444954590000000000000000000000000000000000046a4b4bd41c6b8af100000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: DMMLibrary: INSUFFICIENT_LIQUIDITY\",\n    \"data\": \"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022444d4d4c6962726172793a20494e53554646494349454e545f4c49515549444954590000000000000000000000000000000000046a4b4bd41c6b8af100000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:350264)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:353020)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:353630)\\n    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:3:103441)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:3:104470\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:40731\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:350264)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:353020)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:12:353630)\n  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:3:103441)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:3:104470\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:19:40731"}}
```
