### ISSUE TITLE
Debug: MIMO Pool Rewards via `FuseFlywheelLensRouter`

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#848]
We are using `FuseFlywheelLensRouter.getMarketRewardsInfo()` to get information about the Reward Tokens via a Flywheel and their APY.

This works great for the Jarvis Pool. However, it fails with `TRANSFER_FROM_FAILED` for the MIMO Pool.

We need someone to debug this.

Link: https://app.midascapital.xyz/137/pool/3
Network: `Polygon`
Comptroller: `0xF1ABd146B4620D2AE67F34EA39532367F73bbbd2`
FuseFlywheelLensRouter: `0xACE76A60D4bF76BCa8ccd274Ae6D081904bBbAe3`
Relevant Markets: `0xcb67Bd2aE0597eDb2426802CdF34bb4085d9483A`, `0xa5A14c3814d358230a56e8f011B8fc97A508E890`

---

```
getMarketRewardsInfo(0xF1ABd146B4620D2AE67F34EA39532367F73bbbd2) = CALL_EXCEPTION
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "TRANSFER_FROM_FAILED" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getMarketRewardsInfo(address)", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000145452414e534645525f46524f4d5f4641494c4544000000000000000000000000", errorArgs=["TRANSFER_FROM_FAILED"], errorName="Error", errorSignature="Error(string)", reason="TRANSFER_FROM_FAILED", code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:8591:21)
    at Logger.throwError (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:8600:20)
    at Interface.__webpack_modules__../node_modules/@ethersproject/abi/lib/interface.js.Interface.decodeFunctionResult (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:2384:23)
    at Object.<anonymous> (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:5331:56)
    at step (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:4984:23)
    at Object.next (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:4965:53)
    at fulfilled (/Users/peet/.nvm/versions/node/v16.14.0/lib/node_modules/notar-cli/main.js:4956:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'TRANSFER_FROM_FAILED',
  code: 'CALL_EXCEPTION',
  method: 'getMarketRewardsInfo(address)',
  data: '0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000145452414e534645525f46524f4d5f4641494c4544000000000000000000000000',
  errorArgs: [ 'TRANSFER_FROM_FAILED' ],
  errorName: 'Error',
  errorSignature: 'Error(string)',
  address: '0xACE76A60D4bF76BCa8ccd274Ae6D081904bBbAe3',
  args: [ '0xF1ABd146B4620D2AE67F34EA39532367F73bbbd2' ],
  transaction: {
    data: '0x193bd448000000000000000000000000f1abd146b4620d2ae67f34ea39532367f73bbbd2',
    to: '0xACE76A60D4bF76BCa8ccd274Ae6D081904bBbAe3'
  }
}
```

**Comment by peetzweg** [comment]
fixed
